//+build ignore

package main

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
	"os"
	"path"
	"strings"
	"text/template"
)

const (
	datadir string = "_data"
	confdir string = "pkg/config"
)

type codemap struct {
	Name string `xml:"name"`
	Code string `xml:"code"`
}

func generateCodes(filename string, ctype string) {
	file, err := os.Open(path.Join(datadir, filename))
	if err != nil {
		log.Fatal(err)
	}
	decoder := xml.NewDecoder(file)
	codes := make(map[string]string)

	for {
		t, _ := decoder.Token()
		if t == nil {
			break
		}
		switch se := t.(type) {
		case xml.StartElement:
			if se.Name.Local == ctype {
				var c codemap
				decoder.DecodeElement(&c, &se)
				codes[c.Code] = c.Name
			}
		}
	}
	b, err := json.Marshal(codes)
	if err != nil {
		log.Fatal(err)
	}
	tmpl := template.Must(template.New("").Parse(`
package config

// Code generated by go generate; DO NOT EDIT.
var {{ .Name }} = map[string]string{{ .Code }}`))
	buf := &bytes.Buffer{}
	err = tmpl.Execute(buf,
		struct {
			Name string
			Code string
		}{
			Name: strings.Title(ctype),
			Code: fmt.Sprintf("%s", b),
		})
	if err != nil {
		log.Fatal(err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	err = ioutil.WriteFile(path.Join(confdir, ctype+".go"), src, 0644)
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	os.MkdirAll(confdir, os.ModePerm)
	generateCodes("languages.xml", "language")
	generateCodes("countries.xml", "country")
}
