name: dev ECR push
on:
  push:
    branches:
      - main
# Set defaults
defaults:
  run:
    shell: bash

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "222053980223"
  IAM_ROLE: "timdex-mario-gha-dev"

jobs:
  deploy:
    name: Deploy staging build
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build image
        run: make dist-dev
      - name: Push image
        run: make publish-dev

