name: Tests
on:
  push:
    branches-ignore:
      - main
      - 2.x
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run tests
        run: make test
      - name: Test docker build
        run: make dist-dev
